### ISSUE TITLE
Screen rotation not done correctly for physics on Android

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#1]
### What steps will reproduce the problem?
1. Run an Android demo with physics
2. Turn the screen
3. The old and new physics are mixed together
### What is the expected output? What do you see instead?

The physics should be correct

**Comment by RandomReaper** [comment]
Since @pmudry has fixed it in desktop, it will be less a mess :pray:

**Comment by pmudry** [comment]
I ain't done nothing.

**Comment by pmudry** [comment]
Ah ok I get it... the problem on desktop was a bit different as I only had to *reset* physics, without conserving status. For this bug, physics has to be maintained in the correct state. 

We could also say that rotations are not supported on Android
