### ISSUE TITLE
DemoSelector closes when demo is over

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#10]
When a demo has been chosen in DemoSelector, the application quits after the demo has been closed. It would be nice to be able to choose multiple demos without quitting.

**Comment by pmudry** [comment]
One year later, your skills have improved. You can do it :muscle:

**Comment by metc** [comment]
The about dialog link should be clickable.

**Comment by metc** [comment]
If the flag `forceExit ` of the `LwjglApplicationConfiguration ` (see https://github.com/hevs-isi/gdx2d/blob/master/gdx2d-desktop/src/hevs/gdx2d/lib/PortableApplication.java#L306) is set to `false`, the OpenGL context is lost and demo applications cannot be started again.

It would be great to not call `System.exit` when the game window is closed, so we could select another demo in the selector. How can we fix this ?

**Comment by pmudry** [comment]
I tried to last year, without success. Try your new master's superpowers ;)
