### ISSUE TITLE
Graphic glitch when changing demo

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#100]
In DemoSelector, not easy to fix, comes from the removal of the existing component in the container (I think).

**Comment by RandomReaper** [comment]
Hi @pmudry, 

Congratulations, you've just filled the #100 issue :tada:

**Comment by pmudry** [comment]
Arg... even though I've taught Swing for the 6th consecutive year, I still don't understand how this s***t works. :-1:

**Comment by RandomReaper** [comment]
swing behaves differently on different platform, exactly what we need :100:

**Comment by pmudry** [comment]
Closing, this one sucks too much.
