### ISSUE TITLE
Preparing BitmapImages and Spritessheets outside of PortableApplication interface methods

### ISSUE THREAD

**Issue by Tectu** [hevs-isi/gdx2d#102]
What's the reasoning behind the fact that resources such *BitmapImage* and *Spritesheet* can only be loaded (creating a new instance) within the *onInit()* method?
When trying to prepare an image within the constructor of a custom class the following exception is thrown:
```[GDX2DLib]: error - BitmapImages can only be created in the onInit method of a class extending PortableApplication (or must be called from within this method)```
When implementing classes that represent a unit on a game field it is quite handy to prepare the image resource within the units constructor as the image for that unit never changes (This obviously means that each unit object will have it's own copy of the image which will be memory intensive, but let's not care about that for the moment). If this cannot be done one would have to pass the *BitmapImage* reference through the constructor. When working with multiple classes this can become VERY messy. The class inheriting from *PortableApplication* would have to pass the prepared resources to your GameController class which will again have to pass it to the units which will be created during runtime...

Furthermore, please note that the exception message is not correct. One can create a new instance of said classes within the *onGraphicRender()* method.

As one can create the *BitmapInstance* within the *onGraphicRender()* method my current workaround looks like this (simplified):
```java
public class GameWindow extends PortableApplication {
   onGraphicRender(GdxGraphics g) {
      for (Unit unit : unitsList) {
         unit.render(g)
      }
   }
}

public class Unit {
   private BitmapImage bitmapImage;

   public void render(GdxGraphics g) {
      if (bitmapImage == null) {
         bitmapImage = new bitmapImage("my_dirty_graphics.png");
      }

      g.drawPicture(..., bitmapImage);
   }
}
```

Edit: My custom class does currently not implement the *DrawableObject* interface hence I created my own *render()* method.

**Comment by pmudry** [comment]
Why don't you create your `Unit` in the `onInit` method? This is the sole purpose of the method and solves all your problems. You certainly don't want to do this in the rendering loop.

However, the explanation of why this should be done *once* at the beginning of the program is beyond the scope of this comment. We will discuss this together with pleasure. Briefly, the answer is two-fold:

1. Loading images impact the performance of your game loop severely 
2. Loading resources can't be done anytime on any system (the library works for Android, PC, iOS and the web well).
