### ISSUE TITLE
Separate demos and library

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#103]
Make two projects so that everything is cleaner

**Comment by metc** [comment]
This one is related to #104.
The library will be packed in a separated `jar` so that demo will not be mixed anymore with the gdx2d core library.

**Comment by metc** [comment]
Since version `1.2.0`, the core library and the desktop backend are published on the Maven Central repository (with source files and javadoc) and the snapshots are available on Sonatype. See #104
