### ISSUE TITLE
Publishing the core library to Maven central

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#104]
I propose to publish the core library Jar to the  Maven central repository (to [Sonatype Nexus OSS](http://central.sonatype.org/pages/ossrh-guide.html) for instance). This will:
 1. help to maintain snapshots and release versions,
 2. automating and simplifying our release process,
 2. resolve our build dependencies nightmares between projects,
 3. and finally this will encourage (wide) adoption.

This is a long-term proposal. We can still use `Ant` as build system, or we can switch to `Maven` or `Gradle` but this is not mandatory.

**Comment by pmudry** [comment]
This sounds wonderful. I don't understand the implications though and how the project would be used... Can you elaborate a bit?

**Comment by metc** [comment]
We can now publish any artifacts with the group Id `ch.hevs.*` into the Maven Sonatype repository.

The request was made for another project and we finally get the authorization to publish any `ch.hevs.*` package. That's great, thanks @cm0x4D :notes:

Detailed info available here: https://issues.sonatype.org/browse/OSSRH-16923

**Comment by metc** [comment]
Both `gdx2d-core` and `gdx2d-desktop` artifacts are now available on Maven Central.

See https://repo1.maven.org/maven2/ch/hevs/gdx2d/
The javadoc is available online here: http://www.javadoc.io/doc/ch.hevs.gdx2d/gdx2d-desktop/1.2.0
