### ISSUE TITLE
Coding style guidelines missing

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#114]
We should have  (and define) coding style guidelines, and every contributor should use it.
We use IntelliJ and Eclipse, so I see these two options to achieve this with both IDEs:
 1. We can add an Eclipse code formater. These rules can be used with Eclipse of course and they can also be imported in Intellij ([see this blog post](https://blog.jetbrains.com/idea/2014/01/intellij-idea-13-importing-code-formatter-settings-from-eclipse/)). No plugin are needed.
 2. [editorconfig.org](http://editorconfig.org/) is another possibility. It is supported natively on Github and in all IntelliJ products. Plugins are available for many other tools (Eclipse, Sublime, etc.).

@RandomReaper @pmudry which solution would best fit and who wants to define the guidelines ?

**Comment by RandomReaper** [comment]
[editorconfig.org](http://editorconfig.org/) seems better for me since it is expected to work on more IDE.

**Comment by metc** [comment]
[editorconfig.org](http://editorconfig.org/) allow us to define the charset and indent style but maybe we would need more than that... The Eclipse Code Formatter allow us to configure full coding styles like wrapping, braces, etc.
What do we really need (if any) ?

**Comment by RandomReaper** [comment]
Ahah, I think [editorconfig.org](http://editorconfig.org/) is just a joke :joy:.

The `charset = utf-8` command seems to be the only one useful, and when I say useful, It's for @metc and @pmudry, since my name is 7-bit-ASCII compliant :grin:

**Comment by metc** [comment]
So @RandomReaper, should we use an Eclipse Formatter configuration file ? Would you like to create it ?

**Comment by RandomReaper** [comment]
@metc, feel free to do it and apply it against every file. Just keep in mind I vote against *egyptian brackets* (see http://blog.codinghorror.com/new-programming-jargon/).

**Comment by metc** [comment]
Egyptian brackets style is fine, is usually follow the Java guidelines from Google (see  https://google.github.io/styleguide/javaguide.html).
I will add the Eclipse Formatter file.

**Comment by RandomReaper** [comment]
I gave my opinion, but I will follow the project's CodingStyle.

**Comment by pmudry** [comment]
Hi all,

Egyptian brackets are by default in Java. Please stick to the Java
convention guys, we don't want to reinvent the wheel here (unless it does
not look like the code I've written of course).

Cheers

**Comment by RandomReaper** [comment]
@metc, feel free to add a `.editorconfig` anyway, just for configuring utf-8, it doesn't cost must and can save us some time.

**Comment by metc** [comment]
Both `.editorconfig` and `gdx2d-formatter.xml` files are now available.

The current settings of the formatter are:
 * Indentations with tabs only (according to most of the files)
 * Egyptian brackets style
 * 120 characters line wrapping

Please review this formatter file. Then, I will updated the source code accordingly. This will make a lot of changes btw...
