### ISSUE TITLE
gdx2d desktop library sources

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#117]
The library sources (java files) are useful for the students and must be attached to the library in the hello desktop project.

Unfortunately it is not possible to attach multiple sources roots to a compiled Jar file in Eclipse (IntelliJ supports this feature). Therefore, the source files of the gdx2d core and desktop modules must be aggregate in a single Jar file.

As a temporary fix, the source files of the desktop and core module have been merged manually. This must be done automatically for the next release.

**Comment by pmudry** [comment]
OUch... this seems to be very painful :(
