### ISSUE TITLE
DRXX Eclipse installation missing plugins

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#120]
Several errors with the installed environment in DRXX rooms:

1) Ant `1.8.2` is integrated in Eclipse, but not available in the path, see below:
```sh
christop.metraill@wedrxx:/opt/eclipse-android/current/eclipse/plugins/org.apache.ant_1.8.3.v201301120609/bin$ ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
```

2) Error `Class not found: javac1.8`

```sh
christop.metraill@wedrxx:~/gdx2d/gdx2d-desktop$ /opt/eclipse-android/current/eclipse/plugins/org.apache.ant_1.8.3.v201301120609/bin/ant compile
```

Java `1.8.0_45` is installed. This is a known error with Apache Ant versions less than 1.9.0 - which aren't compatible with Java 8. If you're using a version of Ant < 1.9.0, you should update to a 1.9.x release, see https://bz.apache.org/bugzilla/show_bug.cgi?id=53347

3) The Ant view in Eclipse is missing.

The students are not be able to click on the Ant targets in Eclipse to compile and generate the final `Jar` file.

**Comment by metc** [comment]
![splash](https://cloud.githubusercontent.com/assets/229670/14673928/27a3971c-0701-11e6-9cef-d401e0b94bc3.png)

**Comment by RandomReaper** [comment]
Challange accepted :+1: 
@pmudry could you provide me your fix, so I can deploy it?
Have you thought about the permissions?

**Comment by metc** [comment]
We tested the demo project with the latest Eclipse Mars 2 version, and it worked. The Ant version included in this Eclipse version is compatible with the JDK8. It would be great if you could also add `ant` in the path, so we can build the project with ease from a console.

The Android Development Tools (ADT) is now deprecated in Eclipse. To develop on Android, we should use the Android Studio IDE. Moreover, every `*@hevs.ch` student can use a licence for IntelliJ IDEA Ultimate for free. We should maybe install it too...

**Comment by pmudry** [comment]
Hi,

Please, no IntelliJ right now. 

@RandomReaper I don't have time to make this work sorry. The idea is to downloaded latest Eclipse, put the correct image (which I sent you by email) and maybe update the version in the text. Regarding the permissions, the shared directory in /opt/ should be made read-only as explained in http://help.eclipse.org/juno/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html

Can you both make this work for me ? Don't forget that it should update smoothly for students !!!! This is *very very important*, which means you both should try that for the dummy student account.

Thanks !

**Comment by RandomReaper** [comment]
@pmudry I have misunderstood, I thought you had the archive ready!

About the as smooth as possible:
* It's probably a **bad** idea to change the eclipse version.

About the student accounts:
* ```/etc/skel``` is copied only on the first login, so propagating the configuration will be difficult, unless we
wipe student accounts.

I think it will be smoother/easier to only change/update the missing files.

**Comment by pmudry** [comment]
What is there in skel ? If we just update the Eclipse version, I think
Eclipse just tells you that the existing workspace is an old version and
that you should upgrade it (which is automatic). Could you check this by
going to DRXX, launch existing eclipse, download newest Eclipse, run it and
see what happens ?

**Comment by RandomReaper** [comment]
Do you know which API system images are needed?
Looks like the future update will be 20GB-30GB :sweat:
Do we need "ARM EABI v7a System image", "Google APIs ARM EABI v7a System image" or both for simulation?

**Comment by metc** [comment]
We do not target Android devices any more with the latest version of `gdx2d`.
As I said in a previous comment:

> Important: Support for the Android Developer Tools (ADT) in Eclipse has ended, per our announcement. You should migrate your app development projects to Android Studio as soon as possible. For more information on transitioning to Android Studio, see Migrating from Eclipse ADT.

Source: http://developer.android.com/tools/help/adt.html

**Comment by RandomReaper** [comment]
Something really ugly happened, my old workspace had a non-existent file opened.
The file impossible to open was shown (empty) but directly on the desktop, not in the eclipse window :worried:

@metc, we know that this is deprecated...

I only tested that java and android applications are compiling, and eclipse does not ask where the android sdk is. The and build is successful on the gdx2d desktop demo, but untested.

TODO: 
* Test some labs
* Test that the gdx2d desktop demo is running
* Some other tests

The directory is 21GB...

The test have been done in DR01 on the machine 23.

**Comment by pmudry** [comment]
Just remove Android support. We don't use it anymore in year 1.

**Comment by RandomReaper** [comment]
Will be tested tomorrow!

**Comment by RandomReaper** [comment]
I tested our new eclipse release with gdx2d-1.2.1.zip.
* 5 projects in the archive (a little bit confusing).
* Project references java 1.6 library (only 1.8 in DRxx)
* The ant build file works as expected but warns about missing java 1.6

**Comment by RandomReaper** [comment]
The update is deployed :sweat_smile:

**Comment by RandomReaper** [comment]
Tested on 2 machines, will open another bug if there is a problem with this mars.2 release

**Comment by pmudry** [comment]
Will do, thx!

**Comment by RandomReaper** [comment]
I just had a heart attack, when I saw the email, I though it was the first bug report.

:kissing_cat:

**Comment by metc** [comment]
Thanks Marc gdx2d-library . So the update is available in DR0X ? I just have to start a machine and the magic happens ?

**Comment by RandomReaper** [comment]
sure :+1:
