### ISSUE TITLE
Install documentation no longer up-to-date

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#124]
https://hevs-isi.github.io/gdx2d/doc/install/ relates to the old version. We now have many more projects in the src folder (see #125). 

- The install documentation and images should be updated to explain how to import the demos and the example project.
- A corresponding release note should be done (https://hevs-isi.github.io/gdx2d/news/)

**Comment by metc** [comment]
@pmudry thanks, I will update the website according to your comments.
I will take some screenshots tomorrow using the new environnement freshly installed ;)

**Comment by pmudry** [comment]
You're amazing !

**Comment by metc** [comment]
I added the installation guide and the release note on the website, see https://hevs-isi.github.io/gdx2d/news/release-121/ and https://hevs-isi.github.io/gdx2d/doc/install/
