### ISSUE TITLE
Maven snapshot artifacts are signed

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#129]
The release profile is selected by default even for `SNAPSHOT` versions. Snapshot artifacts should not be signed.

**Comment by metc** [comment]
I added the `release-sign-artifacts` profile (not enabled by default). It is not required and make no sense to sign snapshot artifacts,

**Comment by metc** [comment]
@pmudry I was able to install correctly both `gdx2d-core` and `gdx2d-desktop` snapshot projects (tested with Eclipse in DR01). Could you test this on your side using the `develop` branch ?

**Comment by pmudry** [comment]
Burp
