### ISSUE TITLE
Use CI to build library snapshots

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#130]
To make your lives better, @pmudry proposed to use Travis to build and publish snapshots automatically, in order to add and send new features quickly to the students.

**Comment by pmudry** [comment]
I was able to deploy a snapshot on Sonatype. Automating this task would be great. We should also make the JARs available somewhere on the documentation website as well as the javadoc accessible from the website.

**Comment by pmudry** [comment]
Super duper !
