### ISSUE TITLE
Add the libgdx 'Controllers' extension

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#131]
Several extensions can be imported in libgdx, see https://github.com/libgdx/libgdx/wiki/Dependency-management-with-Gradle#libgdx-extensions

We currently support: 
- [X] Box2D
- [X] FreeTypeFont
- [X] Box2DLights
- [ ] Bullet
- [x] Controllers
- [ ] Tools
- [ ] Ai

Should we add other extensions in gdx2d than Controllers ?

Currently, Box2D, FreeTypeFont and Box2DLights extensions are always packed in the `core` and `desktop` artifacts. Adding other extensions will increase the library size for all users.

**Comment by pmudry** [comment]
Hi,

Controllers should be enough imo, maybe bullet if it's not too big.

Thanks in advance !

**Comment by metc** [comment]
For the `controllers` extension, the gdx2d library will be about 1.3MB bigger:

1.  Core Dependency:
`com.badlogicgames.gdx:gdx-controllers:1.5.6` (11 kB)
2. Desktop Dependency:
`com.badlogicgames.gdx:gdx-controllers-desktop:1.5.6` (22 kB)
`com.badlogicgames.gdx:gdx-controllers-platform:1.5.6:natives-desktop` (1231 kB)

**Comment by metc** [comment]
For the `bullet` extension, the gdx2d library will be about 9.3MB bigger:

1.  Core Dependency:
`com.badlogicgames.gdx:gdx-bullet:1.5.6` (1.3 MB)
2. Desktop Dependency:
`compile "com.badlogicgames.gdx:gdx-bullet-platform:1.5.6:natives-desktop` (8MB)

The current gdx2d desktop library is about 9 MB.

**Comment by metc** [comment]
This is a WIP, see the [controllers-ext](https://github.com/hevs-isi/gdx2d/tree/feature/controllers-ext) feature branch.

**Comment by pmudry** [comment]
We shouldn't include`bullet`then, it would be too big. Thank you for trying though!

**Comment by pmudry** [comment]
Some updates in 593ba03e051af8c6f5ee8e143483fde1dd0f5d66 

The demo still needs some polishing and the ticket can be closed.

**Comment by pmudry** [comment]
Actually the demo is good enough. @metc you can close the issue if that's fine for you.

**Comment by metc** [comment]
I added some drawings in the controllers demo.
We still have some issues regarding the controller extension:

1. The extension does not works with Swing (see #148)
2. Controllers are not enumerated correctly (`onControllerConnected` and `onControllerDisconnected` are not called).

**Comment by metc** [comment]
The controllers extension is will be available in the next release or [in the latest snapshot version](https://oss.sonatype.org/content/repositories/snapshots/ch/hevs/gdx2d/gdx2d-desktop/1.2.2-SNAPSHOT/).
#148 is still an issue.
