### ISSUE TITLE
Drawing texts with rotation

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#138]
The current implementation of the `drawString` primitives cannot be used to draw texts with specific angles.
As a workaround, you can use a `Label`:
```java
com.badlogic.gdx.scenes.scene2d.ui.Label l = new Label("miaou", skin);
l.setWidth(100);
l.setHeight(100);		
		
Container wrapper = new Container(l);
wrapper.setPosition(Gdx.graphics.getWidth() / 2, 100);
wrapper.setTransform(true);
wrapper.setOrigin(wrapper.getPrefWidth() / 2, wrapper.getPrefHeight() / 2);
wrapper.setRotation(45);
```

**Comment by pmudry** [comment]
Hmm... `Label` require the use of `scene2d`which might be a bit overkill for rotating text, no ? Is there no alternative ?

**Comment by metc** [comment]
Currently this is the only way to do it. I think it's possible to apply any `Matrix4` transformation on the SpriteBatch. I will add this feature in the `Game2D` text primitives soon.

**Comment by metc** [comment]
Some tests are available in the [`feature-rotate-font`](https://github.com/hevs-isi/gdx2d/tree/feature/feature-rotate-font) branch. Still need some polishing before merging.

**Comment by metc** [comment]
Will be available in the next release or [in the latest snapshot version](https://oss.sonatype.org/content/repositories/snapshots/ch/hevs/gdx2d/gdx2d-desktop/1.2.2-SNAPSHOT/).
