### ISSUE TITLE
DemoChainPhysics is no longer working in pre-release

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#156]

**Comment by pmudry** [comment]
See https://github.com/libgdx/libgdx/issues/4940

**Comment by Dolu1990** [comment]
It look like the libgdx/libgdx#4940 isn't related to our one, as with 0a1e25d12f26a64a54f49d696dd4f47b4915fb11 it isn't working already.

**Comment by Dolu1990** [comment]
This is the commit that broke things (swing integration + chain physics) 0a7219ef0a89abb4c39ed6abd909d66ee21fe17a
