### ISSUE TITLE
Rescaling does not work correctly

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#21]
Require multiple changes to be handled correctly...Long to implement

**Comment by RandomReaper** [comment]
Rescaling what? you mean supporting different screen size?

**Comment by pmudry** [comment]
Nope, rescaling a window. This is not really important btw as no one uses
that.

**Comment by pmudry** [comment]
Actually it might be important for integrating a PortableApplication into a Swing component. Let's say it's not possible.
