### ISSUE TITLE
Problem for demos on Android

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#6]
Depending on the device, several problem might occur:
- [ ] Scrolling too small (tablet) or too big (Xperia) (for the `DemoScrolling`)
- About box too big (on a tablet it takes too much space) 
- Simple physics dominoes not falling (because the screen is too wide, tablet)
- Alpha image too small for tablet (no repeat)

**Comment by pmudry** [comment]
Performance will be hard to solve. The solution is to use a framebuffer object (i.e. render into a texture and then display it on the screen). This is complicated : https://www.opengl.org/wiki/Framebuffer_Object

Cheers

**Comment by RandomReaper** [comment]
I will split that one too
