### ISSUE TITLE
Various fixes / enhancements 

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#61]
- [ ] Lecture du fichier JSON des démos aussi pour l'application Android
- [ ]  Caméra OpenGL à modifier en fonction de la taille d'écran
- [ ] Optimisations diverse, performances + taille de l'APK (~6 Mo, certains fichiers sont encore dupliqués)
- [ ] Ajouter les nouvelles démos desktop

**Comment by pmudry** [comment]
Duplicate of #58

**Comment by RandomReaper** [comment]
Splitted into #95, #96, #97
