### ISSUE TITLE
AbstractPhysicsObject size error

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#68]
The `DemoPhysicsRocket` is used as an example.
The image `rocket_128.png` is 128x128 pixels. Using this code, the image is drawn with a 0.5 scale (size of  64x64 is correct):
```java
shipImage = new BitmapImage("data/images/rocket_128.png");
g.drawTransformedPicture(pos.x, pos.y, box.getBodyAngleDeg(), .5f, shipImage);
```
![screenshot from 2014-05-14 14 39 00](https://cloud.githubusercontent.com/assets/229670/2971017/e0322bf6-db64-11e3-8371-d143470e913d.png)

The size of the box is 60x60 pixels and not 30x30 like in the code above.
**Ths box is drawn 2x too large.**
```java
box = new PhysicsBox("ship", position, 30, 30, 0.61f, 0.2f, 0.2f);
```

**Comment by pmudry** [comment]
Have a look there @RandomReaper it will give you a first insight on how physics is implemented. Be careful though, :snake: inside and changing things without taking precautions will destroy everything (especially every physics demo).

**Comment by RandomReaper** [comment]
Achievement unlocked : breaking all the demoes ;)

**Comment by pmudry** [comment]
:clap:
