### ISSUE TITLE
Missing /gdx2d-desktop/libs/tween-engine-api.jar

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#77]
/gdx2d-android project references this library : /gdx2d-desktop/libs/tween-engine-api.jar, but it seems unused.
(commit 639c0add59602a86d98c305eba90153b66587e90)

**Comment by metc** [comment]
True. The tween engine was used in the [DemoPositionInterpolator](https://github.com/hevs-isi/gdx2d/blob/master/gdx2d-desktop/src/hevs/gdx2d/demos/tween/interpolatorengine/DemoPositionInterpolator.java) demo.
Now we use the `gdx2d` interpolator.

**Comment by RandomReaper** [comment]
Did you mean I can simply remove this reference?

**Comment by metc** [comment]
Yes just remove it from the project classpath.
It has been done for the desktop projet and not for the Android one (see https://github.com/hevs-isi/gdx2d/commit/3ea7b749cf73c9e9cb2f250db65b62e75aa0a1a6).
