### ISSUE TITLE
Jekyll static site generator

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#78]
In order to centralize the project documentation and to publish Mardown documentation with ease, I propose to setup [Jekyll](http://jekyllrb.com/) to publish static html content to http://hevs-isi.github.io/gdx2d/.

As proposed by @RandomReaper, all the documentation and setup guides will be available on the website (the Github wiki shoulde be removed). Do you agree ?

**Comment by pmudry** [comment]
Do you mean http://hevs-isi.github.io/gdx2d/  ? 

In any case, I agree. The content of the wiki should be put there as well (at least the tutorial on how to start).

**Comment by metc** [comment]
Yes, http://hevs-isi.github.io/gdx2d/ :blush:

**Comment by pmudry** [comment]
I played a bit with the themes etc... This is nice but not very flexible at the moment. Looking forward to have everything there!

**Comment by metc** [comment]
I have built something with [Mkdocs](http://www.mkdocs.org/). It can be a great alternative to build static docs from Mardown files.

**Comment by Cyrillius** [comment]
I am writing a personal website with [ angularJS](https://angularjs.org/) and [Gulp](http://gulpjs.com/) and during my research on internet I fell on this website https://www.staticgen.com/. It could be interesting for you. Maybe you can also use [Grunt](http://gruntjs.com/) or [Gulp](http://gulpjs.com/) to automatted the workflow. It's really great to build an entire website with one command.

**Comment by pmudry** [comment]
@Cyrillius Thanks for the update, sounds promising. We will stick to Jekyll though, as the pages are automatically generated by Github every time we made a change! Cheers!

**Comment by pmudry** [comment]
A sketch of the document is available on the gh-pages branch and online there http://hevs-isi.github.io/gdx2d/ 

The wiki documentation will be migrated soon.

Closing!
