### ISSUE TITLE
Documentation effort for physics

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#79]
You know what to do

**Comment by metc** [comment]
The latest javadoc is available online: http://hevs-isi.github.io/gdx2d/javadoc/latest/
* Look at the [hevs.gdx2d.components.physics](http://hevs-isi.github.io/gdx2d/javadoc/latest/hevs/gdx2d/components/physics/package-summary.html#package_description) and [hevs.gdx2d.components.physics.utils](http://hevs-isi.github.io/gdx2d/javadoc/latest/hevs/gdx2d/components/physics/utils/package-summary.html#package_description) packages.
* Documentation about Box2D is also available in this guide: https://github.com/hevs-isi/gdx2d/blob/mkdocs-wip/docs/intro-guide.md#moteur-physique-box2d

Reopen if necessary.
