### ISSUE TITLE
onGameLogicUpdate method

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#81]
The `onGameLogicUpdate` method is never invoked.

Used only in this demo: https://github.com/hevs-isi/gdx2d/blob/master/gdx2d-desktop/src/hevs/gdx2d/demos/physics/DemoPhysicsBalls.java#L91

**Comment by pmudry** [comment]
It should be left nonetheless. It still makes sense and might be used in a future update. Closing
