### ISSUE TITLE
Contributing and coding style

### ISSUE THREAD

**Issue by metc** [hevs-isi/gdx2d#82]
We should add a `CONTRIBUTING.md` file with general instructions, especially about file encoding and coding styles, which is important and seams to be a big issue for diff.

We use both IntelliJ and Eclipse IDE. What we can do is creating an Eclipse coding style profile (XML file) and publishing it, so we are sure that everybody use the same coding styles (formatter, indentation, whitespaces, braces, line wrapping, etc.). The Eclipse XML profile can also be imported into IntelliJ :notes:

What do you think about creating this Eclipse coding style profile ?

**Comment by pmudry** [comment]
Hey @metc  and @RandomReaper, to solve the coding style issues, I did two things: 

1. I added small comment at the end of the `README.md`
2. I also did uniformize every file in 2efd7282bf4858f4ce2364e855c07cf91001ff0f and made all the changes by myself in IntelliJ. 

I think it is enough, IMO we only have to do this when doing a release. What do you think ?
