### ISSUE TITLE
Tiledmaps are not really well integrated

### ISSUE THREAD

**Issue by AlainWoeffray** [hevs-isi/gdx2d#85]
On the spritesheet demo, the sprite should be paint on the GdxGraphics object and not on the spritebatch.

**Comment by pmudry** [comment]
I am not sure how to do it... Will be done soon though.

**Comment by pmudry** [comment]
Will be done, not for 1.0.1 though

**Comment by pmudry** [comment]
Everything is fine (b7153237e7f4cf2032ed4364f51984ad48519a7f)
