### ISSUE TITLE
Phyiscs in radians, drawTransformedPicture in degrees

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#86]
Proposal : Use the same unit of angular measure for the whole library (I vote for radians :smile: )

**Comment by pmudry** [comment]
Good idea to homogenize this. I vote for minimal change, i.e. if degrees
are everywhere, let's use this (not to break the api too much).

**Comment by RandomReaper** [comment]
opengl uses degree and box2d uses radians, not sure if I want/can change that without introducing bugs and performance problems

**Comment by pmudry** [comment]
We don't change anything then. Closing
