### ISSUE TITLE
ANT generation from Eclipse in DR03 for gdx2d-helloDesktop broken

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#88]
Message : 

`Specified VM install not found: type Standard VM, name jre7`

Computer specific ?

**Comment by RandomReaper** [comment]
Seems to be computer specific, works on my computer.
I will test it in DR03

**Comment by RandomReaper** [comment]
Ant build not working in DR03, will be fixed for the next year

**Comment by pmudry** [comment]
Was working last year, exporting the project is essential. Should be fixed this year, sorry

**Comment by RandomReaper** [comment]
Was working last year before we updated eclipse/android ? :smile:

Challenge accepted :+1:

**Comment by pmudry** [comment]
I think so... at least it is working perfectly on IntelliJ.

**Comment by metc** [comment]
What is the error in the DR03 lab ?
I use these commands and it work well for me (Ubuntu 14 lts):
```bash
$ ant -version
Apache Ant(TM) version 1.9.4 compiled on May 9 2014

$ javac -version
javac 1.6.0_45

$ ant jar
[...]
BUILD SUCCESSFUL
Total time: 3 seconds

$ java -jar dist/gdx2d-helloDesktop.jar 
[GDX2DLib]: gdx2d v1.0.1-RC1, libgdx v1.5.6 | mui, chn, mei (c) 2012-2015
```

**Comment by pmudry** [comment]
There are two problems IMO:

1. ANT seems to be invisible in Eclipse in DR03. Students won't be able to generate the game at the end of the semester. This could easily be fixed by installing ANT in DR03 or make ANT tasks appear on Eclipse (I don't know how though).
2. There is a specific issue on my computer which prevents ANT from working perfectly on Eclipse. This is not a problem. I just tested with a fresh Eclipse install on Linux and it works without a hassle.

**Comment by metc** [comment]
Ant is included as a plugin in Eclipse. It is available in the Eclipse folder under `plugins/org.apache.ant_***`. It is not necessary to install it (maybe add it to the `PATH`).

In Eclipse, use `Window-Show View-Ant` and select the `build.xml` file. Ant tasks are available in the GUI as shown below:
![ant-eclipse](https://cloud.githubusercontent.com/assets/229670/7407840/4c43a07a-ef16-11e4-805a-a9c1f27d7527.png)

I do not have the exactly same settings as in the DR03 lab, but I do not have any issue on my Linux/Windows computers.

**Comment by RandomReaper** [comment]
This problem is specific to the DR03 setup, the Ant plugin is installed, but there is even no `Ant view`.
Probably a mess with the `ADK`.
Installing ant for the command line is a proposed *workaround*, and since I can install ant remotely, this will be done.
If it is possible to fix the eclipse setup in less than 5 clicks, we'll fix eclipse then.

**Comment by RandomReaper** [comment]
Command line ant is now installed in DR03. I change from BUG to IMPROVEMENT, because the export is doable in command line. I will continue investigation in DR03 for eclipse

**Comment by pmudry** [comment]
We don't care. It's working command line. Thank you, closing
