### ISSUE TITLE
URLs not working in DemoSelector

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#91]
At least not under windows

**Comment by metc** [comment]
You mean the URL in the about dialog ? They work on my Linux/Windows computers.

The methods `browse` https://github.com/hevs-isi/gdx2d/commit/1a1f4377d3e9d3b4e1e02a1564537097b9e28476#diff-49bdc360270acddc14ad161017596426R65 look for the associated application registered on the current platform, and launch it to handle a URI or file. If there is no associated application or the associated application fails to be launched, an exception is thrown.

**Comment by pmudry** [comment]
Working on most of my computers. Sorry.... closing
