### ISSUE TITLE
Icons in taskbar not displayed in Unity (Ubuntu)

### ISSUE THREAD

**Issue by pmudry** [hevs-isi/gdx2d#92]
A ? is displayed instead, working on Windows

**Comment by metc** [comment]
This is a known bug from last year, unfortunately no resolved yet... See https://github.com/LWJGL/lwjgl/issues/68

**Comment by metc** [comment]
Look also here https://github.com/hevs-isi/gdx2d/issues/19

**Comment by pmudry** [comment]
Thanks for the refresh.... Go to hell Unity, you don't deserve our time. Closing.
