### ISSUE TITLE
Android apk size could be reduced

### ISSUE THREAD

**Issue by RandomReaper** [hevs-isi/gdx2d#96]
Split of #61

**Comment by pmudry** [comment]
Reducing size requires a nightmare of configuration of obscure optimizer options... :-1: We don't really care.

**Comment by RandomReaper** [comment]
90% of the apk size is assets/*, not classes !

**Comment by metc** [comment]
Proguard will not remove files from the `asset` folder, but using `lint --check UnusedResources` we can find all unused resources.

For the `gdx2d-helloAndroid` project, all demo assets can be safely removed. We just need the default fonts, logo and icons.
